version: '3.7'

services:
  app:
    image: rodlopez/demo-ec2-nestjs:v1
    container_name: demo_nestjs
    env_file: .env
    ports:
      - 80:4000
    depends_on:
      - mongodb
    restart: always
    networks:
      - demo_nw_nestjs
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - demo_nw_nestjs

volumes:
  mongodb:

networks:
  demo_nw_nestjs:
    